Домашнє завдання №1

23 варіант

In [10]:
import numpy as np

1.	Створіть одновимірний масив (вектор) зі значеннями квадратних коренів з кожного натурального числа, починаючи з 1, та виведіть його значення.

In [11]:
a = np.sqrt(np.arange(1, 11))
print(a)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями залишків від ділення кожного числа на 3, починаючи з 1, та виведіть його значення.

In [12]:
a = np.arange(1, 10).reshape(3, 3) % 3
print(a)

[[1 2 0]
 [1 2 0]
 [1 2 0]]


3. Створіть масив розміром 9x9, заповніть його випадковими натуральними числами від 1 до 50 та знайдіть відсоток чисел, які діляться на 3 без остачі.

In [13]:
a = np.random.randint(1, 51, size=(9,9))
n = ((np.sum(a % 3 == 0)) / 81) * 100
print(a)
print("Відсоток чисел, які діляться на 3 без остачі:")
print(n)

[[11 45 43  5 32 37 23 19 49]
 [19 24  6 22 41 38  1 47 18]
 [ 6 31 41  6  9 10 39 13 12]
 [41 21  4  8 49  5  1 22 49]
 [ 1 42 13 30 27 46 21 25 45]
 [13 45 31 19 26  1 39 26 11]
 [ 3 35 18  1 23 11 12  7  9]
 [50 44 43 38 14 32 15 44 32]
 [35 12 27  7 49 18 17 31 37]]
Відсоток чисел, які діляться на 3 без остачі:
30.864197530864196


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.9 до 0.9 та виведіть його значення.

In [14]:
a = np.random.uniform(-0.9, 0.9, size=(4, 4))
print(a)

[[ 0.83444976 -0.10318941  0.48729698  0.17563839]
 [-0.24551515  0.2315531   0.24469875 -0.8189411 ]
 [-0.67715476 -0.79043632 -0.19558915 -0.8178614 ]
 [ 0.70332138  0.18937658  0.48037856 -0.37763678]]


5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.

In [15]:
a = np.random.randint(1, 6, size=7)
b = np.random.randint(1, 6, size=7)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

a =  [3 1 2 2 4 4 2]
b =  [2 5 4 4 4 2 5]
a + b =  [5 6 6 6 8 6 7]
a - b =  [ 1 -4 -2 -2  0  2 -3]
a * b =  [ 6  5  8  8 16  8 10]


6. Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток.

In [16]:
a = np.random.randint(1, 11, size=4)
b = np.random.randint(1, 11, size=4)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів дорівнює:", dot_a_b)

a =  [1 2 7 3]
b =  [3 2 9 3]
Скалярний добуток векторів дорівнює: 79


7. Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 15 та перемножте їх між собою.

In [17]:
a = np.random.randint(1, 16, size=(2, 3))
b = np.random.randint(1, 16, size=(3, 4))

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Результат множення матриць:")
print(dot_a_b)

a =  [[14  8  6]
 [12 13  5]]
b =  [[13  6 10  9]
 [11 14 10  2]
 [11  8 15  7]]
Результат множення матриць:
[[336 244 310 184]
 [354 294 325 169]]


8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [18]:
a = np.random.randint(1, 16, size=(2, 2))
print("Вихідна матриця:")
print(a)
if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)


Вихідна матриця:
[[15 13]
 [11  4]]
Обернена матриця:
[[-0.04819277  0.15662651]
 [ 0.13253012 -0.18072289]]


9. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 3 до 15 та транспонуйте її.

In [19]:
a = np.random.randint(1, 16, size=(3, 3))
print(a)

a_transp = np.transpose(a)
print("Транспонована матриця:")
print(a_transp)

[[ 4  8  5]
 [ 1  8 13]
 [ 6 10 14]]
Транспонована матриця:
[[ 4  1  6]
 [ 8  8 10]
 [ 5 13 14]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму добутків елементів кожного стовпця матриці на відповідний елемент вектору.

In [20]:
matr = np.random.randint(1, 10, size=(3, 4))
vect = np.random.randint(1, 10, size=4)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.sum(matr * vect, axis=0)
print(result)

Матриця:
[[5 4 3 5]
 [7 6 9 7]
 [6 9 3 5]]
Вектор:
[2 4 1 2]
Результат множення матриці на вектор:
[36 76 15 34]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток вектора на матрицю.

In [21]:
matr = np.random.rand(2, 3)
vect = np.random.rand(3)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[0.83783801 0.62437998 0.52534257]
 [0.53973185 0.40476981 0.64722045]]
Вектор:
[0.95603478 0.32224754 0.24498375]
Результат множення матриці на вектор:
[1.13090758 0.80499699]


12. Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток всіх елементів першої матриці.

In [22]:
a = np.random.randint(1, 11, size=(8, 8))
b = np.random.randint(1, 11, size=(8, 8))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Поелементне множення через multiply:")
result = np.multiply(a, a)
print(result)
r_2 = np.prod(a)
print(r_2)

Перша матриця:
[[ 8 10  1  8  3  3  1  9]
 [ 5  4  7  3  9  9  7  9]
 [ 4  1  7  1  2  6 10  2]
 [ 8  1  2  5 10  1  9  5]
 [ 1  8  5  7  3  3 10  1]
 [ 9  8  2  2  7  1  9  5]
 [10  5 10 10  6 10  5  9]
 [ 4 10  1  7  3  6  5  3]]
Друга матриця:
[[ 2 10  4  6  3  8  2  3]
 [10 10  9 10  7  5  6  3]
 [ 4  5  8  9  4  8  2  1]
 [ 3  1  8  8  7  4  2  6]
 [ 6  7  4 10  7  6  6  3]
 [ 9  3  7  5  8  2  4  1]
 [ 8  6  2  3 10  8  2  5]
 [ 7  1  7  3  2  7  8  5]]
Поелементне множення через multiply:
[[ 64 100   1  64   9   9   1  81]
 [ 25  16  49   9  81  81  49  81]
 [ 16   1  49   1   4  36 100   4]
 [ 64   1   4  25 100   1  81  25]
 [  1  64  25  49   9   9 100   1]
 [ 81  64   4   4  49   1  81  25]
 [100  25 100 100  36 100  25  81]
 [ 16 100   1  49   9  36  25   9]]
0


13. Створіть дві матриці розміром 7x7, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть різницю їх елементів.

In [23]:
a = np.random.uniform(-1, 1, size=(7, 7))
b = np.random.uniform(-1, 1, size=(7, 7))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Різниця матриць:")
result = a - b
print(result)

Перша матриця:
[[ 0.93543558 -0.54661994 -0.51262255 -0.45485193 -0.63663177 -0.62532604
   0.42473955]
 [ 0.64389692 -0.5732884   0.63587471 -0.02421094  0.83491528 -0.7160741
   0.6746104 ]
 [-0.76174658  0.48225996 -0.06039746  0.45219654  0.8308672  -0.80977891
  -0.26792813]
 [ 0.15808616  0.39350919  0.87656827 -0.20231248 -0.61645389  0.31306046
  -0.29563025]
 [-0.93411135 -0.37429392 -0.90773123  0.73839162 -0.28395887  0.49640294
   0.62114677]
 [-0.89230987 -0.25597232  0.94917903 -0.58748611 -0.74908529 -0.94472929
   0.52634092]
 [ 0.09192097 -0.73875382 -0.17977113 -0.23151608  0.33282751  0.44949479
  -0.28618655]]
Друга матриця:
[[-0.60860332  0.96698815  0.66835023 -0.14166399  0.00817702 -0.94142297
  -0.98412433]
 [ 0.79870906  0.88799547  0.73026825 -0.18173077 -0.76917917  0.01360793
  -0.27396614]
 [-0.49585603  0.11398151 -0.84920815  0.37305042 -0.58457364 -0.78529877
  -0.14932089]
 [ 0.68099866  0.82137615 -0.6163101   0.29162199  0.73920171 -0.63735816
   0.9

14.	Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть суму елементів на головній діагоналі.

In [24]:
a = np.random.uniform(-10, 10, size=(9, 9))
result = np.trace(a)
print("Матриця")
print(a)
print("Сума елементів на головній діагоналі:")
print(result)

Матриця
[[-7.45862999 -0.08272209 -4.16527484  0.49245672  7.21088834 -8.64762981
  -7.61950884 -9.88365383 -0.364888  ]
 [-4.90043062 -4.23504588  6.17829882  6.73999713 -3.66673374 -4.93964061
  -7.43556114  9.82941198 -6.64101509]
 [ 6.45155276  1.1902489  -7.92570372 -9.02039982  1.58901481 -5.30802849
  -7.24930203  1.27383117 -6.34585659]
 [ 6.45723479  9.00940934  7.75427692 -4.29863974  9.7304714  -4.90487775
   5.08472852  2.49083103  3.09481994]
 [-1.4485036  -9.2117513  -4.84946477 -1.35702727 -4.13449561 -7.83503153
  -4.95283883  4.75273009  7.25702393]
 [-0.39623388  0.38696932  0.77839231 -4.05492246  7.84736165  0.12603889
  -2.54502998 -3.6520265   5.49776172]
 [-1.75275663  6.11066771  8.9434896  -5.84122958 -5.9216661   3.72307355
   0.20418426 -2.73477449  2.88399073]
 [-9.18909531 -9.31217905  9.67530376  9.27079092  1.18340801 -8.69052679
   7.44049419  5.36998019  4.5552662 ]
 [ 5.9230066   4.42354779 -1.24913303 -3.88661751  2.73486562 -1.5517395
   1.64169742 -

15.	Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці.

In [25]:
a = np.random.uniform(-0.5, 0.5, size=(9, 9))
print("Перша матриця:")
print(a)
column_sums = a.sum(axis=0)
col_vec = column_sums.reshape((-1, 1))
print("Вектор-стовпчик з сумами елементів кожного стовпця:")
print(col_vec)

Перша матриця:
[[ 0.27933177 -0.06091074  0.4112234   0.08185357  0.15639886 -0.31995984
   0.46602878 -0.40540743  0.09972324]
 [-0.11203756  0.02966959 -0.33128328  0.14874179  0.31503592 -0.06534702
   0.44623753  0.00644529  0.36132977]
 [-0.39769547 -0.34376992 -0.05777074  0.2583286   0.09723049  0.25051549
  -0.32905033  0.28346353 -0.17369597]
 [-0.37084346 -0.13910679  0.11036205  0.26282059 -0.31679885 -0.09151224
  -0.29045315  0.48893347 -0.43365783]
 [ 0.06169003  0.33280787  0.11837717 -0.49815188  0.35978884 -0.12401695
   0.06081266 -0.41370885 -0.02213637]
 [ 0.0683377  -0.23369561  0.20940847  0.25583293 -0.47934302  0.38479062
   0.02309597  0.09344064  0.26855737]
 [ 0.34911659 -0.07752979  0.1784869   0.41015483  0.42126174 -0.39031891
  -0.04021671 -0.32230659  0.39158186]
 [-0.15576299  0.30941353  0.09066758  0.23471553 -0.48848986 -0.12656015
  -0.3791586  -0.28770894  0.40453186]
 [-0.09884646  0.13008334 -0.09126142 -0.27161613  0.09598892 -0.29169238
   0.30

В практичній роботі була використана бібліотека numpy. Також для вирішення завдань були використані такі функції бібліотеки, як arange, reshape, random, randint, uniform та інші